baseurl = "https://berghofsociety.github.io/BerghofSociety/"
# remember trailing / ^^^^^^^^^^^^^^^^^^^^^^^^
languageCode = "en-us"
title = "Enzo Zeffi | Diary"
# Enable comments by entering your Disqus shortname
# disqusShortname = ""
# Enable Google Analytics by entering your tracking code
# googleAnalytics = ""
paginate = 25
theme = "custom-theme"

[markup.goldmark.renderer]
unsafe= true

[permalinks]
	post = "/:year/:month/:day/:slug"

[params]
	name = "Enzo Zeffi"
	description = ""
	copyright = ""

	# Custom assets can be linked with their paths relative to static/
	custom_css = []
	custom_js  = []

	# Links to newer/older blog posts
	newer = "Newer"
	older = "Older"

	pageNotFoundTitle = "Page not found"
	pageNotFoundSubtitle = "The requested page was not <br> found on the server."

[params.offcanvas]
	# Menu items
	title = "Enzo Zeffi"
	bio = "PO Box 1016"
	bio2 = "San Francisco, CA 94117"
	subscribe = "Subscribe"
	followme = "Contact"

	# Enable Google search
	search_enabled = true
	search = "Search"

	[[params.offcanvas.socialnetworks]]
		name = "enzozeffi@protonmail.ch"
		url = "mailto:enzozeffi@protonmail.ch"
